debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.fsapi: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FSapi?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: sungsu@0521
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul
  sql.init.mode: always #data.sql 생성
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha